#!/bin/bash

$( dirname $0 )/shutdown

set -e

HOME=/vagrant/push
BUILDDIR=/tmp/staged/app
CACHEDIR=/tmp/cache
BUILDPACKDIR=/vagrant

mkdir -p ${BUILDDIR} ${CACHEDIR}
rsync -aq ${HOME}/ ${BUILDDIR}

ruby ${BUILDPACKDIR}/bin/compile ${BUILDDIR} ${CACHEDIR}

rm -rf /app/*
rsync -aq ${BUILDDIR}/ /app
